name: Bump Homebrew Tap on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump formula in tap
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # PAT with "repo" scope, stored in your main repo secrets
          token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          # Your tap repository
          tap: yeboahmedia/tools
          # Formula name (without .rb)
          formula: pull-apk
          # Tag being released
          tag: ${{ github.ref_name }}
          # Tarball URL from GitHub
          download-url: https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz
          force: true
