name: Bump Homebrew Tap on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump formula in tap
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          tap: yeboahmedia/tools
          formula: pull-apk
          tag: ${{ github.ref_name }}
          force: true
